# Homework 0 - Deep Learning Winter 2024
TA: Jerry Abu Ayoub

Student 1: Samih Warwar 324888155

Student 2: Merry Shalabi 324007202

**Submission Date and time: 28/11/2024 23:59**

Submission is in pairs only, delayed submissions will result in a 5 point deduction each day for maximum of 3 days.

in this assignment, you will experiment with some basic pytorch functions to manipulate data to understand the fundementals. read the text boxes and write your code in the code cells below to answer the questions and run the cells, when you finish all tasks, save the notebook and submit it in the course website.

submission notebook should have all code cells already run with their respective outputs, submitting notebooks with unrunned cells will also result in point deductions.

## Data Manipulation

It is impossible to get anything done if we cannot manipulate data. Generally, there are two important things we need to do with data: (i) acquire it and (ii) process it once it is inside the computer. There is no point in acquiring data if we do not even know how to store it, so let's get our hands dirty first by playing with synthetic data. We will start by introducing the tensor,
PyTorch's primary tool for storing and transforming data. If you have worked with NumPy before, you will notice that tensors are, by design, similar to NumPy's multi-dimensional array. Tensors support asynchronous computation on CPU, GPU and provide support for automatic differentiation.

## Getting Started

In the cell below import torch and any other libraries you want to use.

In [28]:
import torch

Tensors represent (possibly multi-dimensional) arrays of numerical values.
The simplest object we can create is a vector.

To start, use `arange` to create a row vector with 12 consecutive integers.

In [29]:
# write your code here
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Print the shape of the tensor

In [30]:
# We can get the tensor shape through the shape attribute.
print(f'The shape of the tensor is {x.shape}')


The shape of the tensor is torch.Size([12])


use 'size' to print the shape of the tensor again

In [31]:
# .shape is an alias for .size(), and was added to more closely match numpy
print(f'The shape of the tensor is {x.size()}')



The shape of the tensor is torch.Size([12])


We use the `reshape` function to change the shape of one (possibly multi-dimensional) array, to another that contains the same number of elements.
For example, we can transform the shape of our line vector `x` to (3, 4), which contains the same values but interprets them as a matrix containing 3 rows and 4 columns. Note that although the shape has changed, the elements in `x` have not.

reshape the vector into a 3x4 martix and print the result

In [32]:
# write your code here

x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaping by manually specifying each of the dimensions can get annoying. Once we know one of the dimensions, why should we have to perform the division our selves to determine the other? For example, above, to get a matrix with 3 rows, we had to specify that it should have 4 columns (to account for the 12 elements). Fortunately, PyTorch can automatically work out one dimension given the other.
We can invoke this capability by placing `-1` for the dimension that we would like PyTorch to automatically infer.

In our case, instead of
`x.reshape((3, 4))`, use `-1` to reshape the tensor.

In [33]:
x.reshape(3,-1)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

create a 2x3 float tensor

In [34]:
y=torch.FloatTensor(2,3)
y


tensor([[2.2499e+32, 4.4331e-41, 4.5939e+22],
        [3.2549e-41, 4.4842e-44, 0.0000e+00]])

torch.Tensor() is just an alias to torch.FloatTensor() which is the default type of tensor, when no dtype is specified during tensor construction.

From the torch for numpy users notes, it seems that torch.Tensor() is a drop-in replacement of numpy.empty()

So, in essence torch.FloatTensor() and torch.empty() does the same job.

The `empty` method just grabs some memory and hands us back a matrix without setting the values of any of its entries. This is very efficient but it means that the entries might take any arbitrary values, including very big ones! Typically, we'll want our matrices initialized either with ones, zeros, some known constant or numbers randomly sampled from a known distribution.

Perhaps most often, we want an array of all zeros.

Create a 2x3x4 multidimensional tensor with all entries as zeros.

In [35]:
multi_zero=torch.zeros(2,3,4)
multi_zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Create a 2x3x4 tensor with all entries as ones

In [36]:
multi_one=torch.ones(2,3,4)
multi_one

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We can also specify the value of each element in the desired NDArray by supplying a Python list containing the numerical values.

create a 2d tensor with the following lists as entries:
[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]


In [37]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In some cases, we will want to randomly sample the values of each element in the tensor according to some known probability distribution. This is especially common when we intend to use the tensor as a parameter in a neural network.

write a snippet that creates a tensor with a shape of (3,4). Each of its elements is randomly sampled in a normal distribution with zero mean and unit variance.

In [38]:
random_normal=torch.randn(3,4)
random_normal

tensor([[ 0.3305, -1.6284,  0.4703,  1.3775],
        [ 1.0886,  1.4629, -0.7077, -1.1917],
        [-0.0380,  1.0063,  0.5186,  0.1144]])

## Operations

Oftentimes, we want to apply functions to arrays. Some of the simplest and most useful functions are the element-wise functions. These operate by performing a single scalar operation on the corresponding elements of two arrays. We can create an element-wise function from any function that maps from the scalars to the scalars. In math notations we would denote such a function as $f: \mathbb{R} \rightarrow \mathbb{R}$. Given any two vectors $\mathbf{u}$ and $\mathbf{v}$ *of the same shape*, and the function f,
we can produce a vector $\mathbf{c} = F(\mathbf{u},\mathbf{v})$ by setting $c_i \gets f(u_i, v_i)$ for all $i$. Here, we produced the vector-valued $F: \mathbb{R}^d \rightarrow \mathbb{R}^d$ by *lifting* the scalar function to an element-wise vector operation. In PyTorch, the common standard arithmetic operators (+,-,/,\*,\*\*) have all been *lifted* to element-wise operations for identically-shaped tensors of arbitrary shape. We can call element-wise operations on any two tensors of the same shape, including matrices.

create a float tensor "x" that has: 1 2 4 8 and an another tensor "y" of all 2s

compute and print the element wise operations of addition, subtraction, multiplication, division and exponentiation e^(for both tensors)


In [39]:
# write your code here

x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(torch.exp(x))
print(torch.exp(y))

tensor([ 3,  4,  6, 10])
tensor([-1,  0,  2,  6])
tensor([ 2,  4,  8, 16])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([7.3891, 7.3891, 7.3891, 7.3891])


In addition to computations by element, we can also perform matrix operations, like matrix multiplication using the `mm` or `matmul` function. Next, we will perform matrix multiplication of `x` and the transpose of `y`. We define `x` as a matrix of 3 rows and 4 columns, and `y` is transposed into a matrix of 4 rows and 3 columns. The two matrices are multiplied to obtain a matrix of 3 rows and 3 columns.

define x as a 3x4 matrix with consecutive numbers from 0 to 11 and let y be a 2d array with the following lists as entries:

[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]

print the type of the tensors and print the multiplication of x and y transpose

In [40]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(x.dtype)
print(y.dtype)
print(torch.matmul(x,y.T))

torch.int64
torch.int64
tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])


Note that torch.dot() behaves differently to np.dot(). There's been some discussion about what would be desirable here. Specifically, torch.dot() treats both x and y as 1D vectors (irrespective of their original shape) and computes their inner product.

We can also merge multiple tensors. For that, we need to tell the system along which dimension to merge.

merge the previous two matrices along the row axis and column axis respectively.

In [41]:
row_mul = torch.cat((x,y),dim=0)
print(row_mul)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])


In [42]:
col_mul = torch.cat((x,y),dim=1)
print(col_mul)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])


construct a binary tensors via logical element wise equation, that is the entry is 1 if and only if the 2 elements are equal in the same position, otherwise its zero.

use tensors x and y and compute the binary tensor.

In [43]:
binary_tensor = torch.eq(x, y).int()
binary_tensor

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

Summing all the elements in the tensor yields an tensor with only one element.

Sum all of x's elements

In [44]:
sum_x = x.sum()
sum_x

tensor(66)

## Broadcast Mechanism

In the above section, we saw how to perform operations on two tensors of the same shape. When their shapes differ, a broadcasting mechanism may be triggered analogous to NumPy: first, copy the elements appropriately so that the two tensors have the same shape, and then carry out operations by element.

In [45]:
a = torch.arange(3, dtype=torch.float).reshape((3, 1))
b = torch.arange(2, dtype=torch.float).reshape((1, 2))
a, b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

Since `a` and `b` are (3x1) and (1x2) matrices respectively, their shapes do not match up if we want to add them. PyTorch addresses this by 'broadcasting' the entries of both matrices into a larger (3x2) matrix as follows: for matrix `a` it replicates the columns, for matrix `b` it replicates the rows before adding up both element-wise.

add a and b and see for yourself

In [46]:
sum_ab = a + b
sum_ab

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

## Indexing and Slicing

Just like in any other Python array, elements in a tensor can be accessed by its index. In good Python tradition the first element has index 0 and ranges are specified to include the first but not the last element.

use the ":' operand to select and print the first and second rows in x

In [47]:
print(f'First and second row:\n {x[0:2]}')

First and second row:
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


Beyond reading, we can also write elements of a matrix like usual

write 9 in position 1,2 in x and print x

In [48]:
x[1,2] = 9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

use slicing to write 12 in the first and second rows of the matirx

In [49]:
x[0:2, :] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

## Saving Memory

In the previous example, every time we ran an operation, we allocated new memory to host its results. For example, if we write `y = x + y`, we will dereference the matrix that `y` used to point to and instead point it at the newly allocated memory. In the following example we demonstrate this with Python's `id()` function, which gives us the exact address of the referenced object in memory. After running `y = y + x`, we will find that `id(y)` points to a different location. That is because Python first evaluates `y + x`, allocating new memory for the result and then subsequently redirects `y` to point at this new location in memory.

use id() to check if the first y tensor is in the same memory of the resul y tensor

In [50]:
before = id(y)
y = y + x
id(y) == before

False

This might be undesirable for two reasons. First, we do not want to run around allocating memory unnecessarily all the time. In machine learning, we might have hundreds of megabytes of parameters and update all of them multiple times per second. Typically, we will want to perform these updates *in place*. Second, we might point at the same parameters from multiple variables. If we do not update in place, this could cause a memory leak, making it possible for us to inadvertently reference stale parameters.

Fortunately, performing in-place operations in PyTorch is easy. We can assign the result of an operation to a previously allocated array with slice notation, e.g., `y[:] = <expression>`. To illustrate the behavior, we first clone the shape of a matrix using `zeros_like` to allocate a block of 0 entries.

allocate a block of zeroes into a tensor named z, print the id of z, perfomr the addition of x and y into z and print the id of z again.

In [51]:
z= torch.zeros_like(y)
before = id(z)
print('id before:', before)
z[:] = x + y
print('id after:',id(z))
id(z) == before

id before: 135876406005888
id after: 135876406005888


True

## Mutual Transformation of PyTorch and NumPy

Converting PyTorch Tensors to and from NumPy Arrays is easy. The converted arrays do *not* share memory. This minor inconvenience is actually quite important: when you perform operations on the CPU or one of the GPUs, you do not want PyTorch having to wait whether NumPy might want to be doing something else with the same chunk of memory. `.tensor` and `.numpy` do the trick.

convert "a" to a torch tensor and put in "b" then print b's type to ensure it's a tensor

In [52]:
# Write your code here
a = x.numpy()
print(type(a))
b = torch.from_numpy(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


## Usage of Latex and Mathematics notations, usage of Autograd in pytorch

Use Latex to write down the 2 variable bell function (Recall from calculus 2), write it in understandable tidy mathematical formation (the most simple one).

-- your function in Latex should appear here --
$$f(x, y) = e^{-(x^2 + y^2)}$$

Use Latex again to write the gradient of the function, it should appear in a nice understandable mathematical format.

-- your function's gradient in Latex should appear here --
$$\nabla f(x, y) = \left( -2x e^{-(x^2 + y^2)}, -2y e^{-(x^2 + y^2)} \right)$$

write a piece code in the cell below using pytorch to do the following:

- define the bell function
- print it's value at (0,0) and (1,1)
- print the gradient's value at those points

In [53]:
def bell_function(x, y):
  return torch.exp(-(x**2 + y**2))

x_vals = torch.tensor([0.0, 1.0], requires_grad=True)
y_vals = torch.tensor([0.0, 1.0], requires_grad=True)

for i in range(2):
    function_value = bell_function(x_vals[i], y_vals[i])
    print(f"Function value at ({x_vals[i].item()}, {y_vals[i].item()}): {function_value.item()}")

# grad
for i in range(2):
  function_value = bell_function(x_vals[i],y_vals[i])
  function_value.backward()
  print(f"Gradient at ({x_vals[i].item()}, {y_vals[i].item()}):",
        (x_vals.grad[i].item(),y_vals.grad[i].item()))
  x_vals.grad.zero_()
  y_vals.grad.zero_()

Function value at (0.0, 0.0): 1.0
Function value at (1.0, 1.0): 0.1353352814912796
Gradient at (0.0, 0.0): (-0.0, -0.0)
Gradient at (1.0, 1.0): (-0.2706705629825592, -0.2706705629825592)
